openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
  description: "**Описание API**"
  termsOfService: "degray848484@gmail.com"
  contact:
    name: "Skarmind"
    email: "degray848484@gmail.com"
servers:
  - url: https://api.json-generator.com/templates/RWuceH2LVDQC
    description: "production server"
  - url: https://api.json-generator.com/templates/RWuceH2LVDQS
    description: "staging server"

components:
  schemas:
    name:
      type: object
      properties:
        property:
          type: integer
  securitySchemes:
    name:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /data:
    get:
      responses:
        "200":
          description: OK
security:
  - name: []
